---
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec: 
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31200
  selector:
    run: gop-fileserver
  type: NodePort