--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drupal
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  strategy: {}
  template:
    metadata:
      labels:
        app: drupal
    spec:
      initContainers:
      - image: drupal:8.6
        name: init-sites-volume
        command: [ "/bin/bash", "-c" ]
        args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
        volumeMounts:
        - name: data
          mountPath: '/data'
      containers:
      - image: drupal:8.6
        name: drupal
        volumeMounts:
        - name: data
          mountPath: '/var/www/html/modules'
          subPath: modules
        - name: data
          mountPath: '/var/www/html/themes'
          subPath: themes
        - name: data
          mountPath: '/var/www/html/sites'
          subPath: sites
        - name: data
          mountPath: '/var/www/html/profiles'
          subPath: profiles
        resources: {}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: drupal-pvc