---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: jekyll
  name: jekyll
  namespace: development
spec:
  initContainers:
  - image: kodekloud/jekyll
    name: copy-jekyll-site
    command: [ "jekyll", "new", "/site" ]
    volumeMounts:
    - name: site
      mountPath: "/site"
  containers:
  - image: kodekloud/jekyll-serve
    name: jekyll
    resources: {}
    volumeMounts:
    - name: site
      mountPath: "/site"
  volumes:
  - name: site
    persistentVolumeClaim:
      claimName: jekyll-site
  dnsPolicy: ClusterFirst