---
apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
spec: 
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 4000
    nodePort: 30097
  selector:
    run: jekyll
  type: NodePort